packages:
  - "apps/*"
  - "packages/*"
  - "packages/weaver/*"
  - "tests/*"
allowBuilds:
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  protobufjs: false
  sharp: true
  unrs-resolver: true
